### ISSUE TITLE
parameterized paths

### ISSUE THREAD

**Issue by pmcelhaney** [pmcelhaney/counterfact#1]
Sometimes a parameter appears in the middle of a path, e.g.:

```
/users/{user_id}/profile
/users/{user_id}/friends
/users/{user_id}/preferences
```

The filesystem based routing scheme doesn't currently accommodate this use case well. Ideally we would model the above like so:

```
- users
   - user_id
       - friends.js
       - preferences.js
       - profile.js
 ```
  

But that will only match these URLs

```
/users/user_id/friends
/users/user_id/preferences
/users/user_id/profile
 ```

Whereas we want it to match URLs that look like this:

```
/users/12345/friends
/users/12345/preferences
/users/12345/profile

/users/86753/friends
/users/86753/preferences
/users/86753/profile

/users/99999/friends
/users/99999/preferences
/users/99999/profile
```

We need a way to identify that the `user_id` directory is a wildcard, not meant to be matched literally. Where would be the right place to encode that information? How about in `user.js`?

```
- users
   - user_id
       - friends.js
       - preferences.js
       - profile.js
- users.js <--- here
 ```

```js
// users.js 
const USER_ID_REGEX = /^\d{3,10}$/;

export function wildcard(key) {
   if(USER_ID_REGEX.test(key) { 
       return 'user_id';
   } 
   return key;
}
```

When parsing the URL `/users/99999/profile`, Counterfact will look at users.js and find that it has a wildcard function. Since "99999" is a valid user ID, it will next look for `./users/user_id.js` and `./users/user_id/profile.js` instead of `./users/99999.js` and `./users/99999/profile.js`

Profile.js will then look something like this:
```js
//profile.js

export function GET({path, store}) {
   return {
      body: `User profile for ${path.user_id}: ${store.users[path.user_id].profile}`
   }
}

export function PUT({path, store, body}) {
    store.users[path.user_id].profile = body;
   return {
      body: `ok`
   }
}

```

**Comment by pmcelhaney** [comment]
Here's the new logic to look up the most specific matching GET/POST/PUT/PATCH/DELETE function. (I have not tested this code. It's a spike that I plan to rewrite with TDD.)

```js
 endpoint(method, url) {
    function findHandler(tree, path, fallback) {
      const handler = tree.script?.[method] ?? fallback;

      if (path.length === 0) {
        return handler;
      }

      if (tree.children[path[0]]) {
        return findHandler(tree.children[path[0]], path.slice(1), handler);
      }

      const wildcard = tree.script?.wildcard?.(path[0]);

      if (wildcard) {
        return findHandler(wildcard, path.slice(1), handler);
      }

      return handler;
    }

    function notFoundFallback() {
      return {
        status: 404,
        body: `${method} method for endpoint at "${url}" does not exist`,
      };
    }

    return findHandler(
      this.moduleTree,
      url.split("/").slice(1),
      notFoundFallback
    );
  }
```

**Comment by KameronKales** [comment]
Im not sure if you've ever seen how next.js does this, but I really like it. https://nextjs.org/docs/routing/dynamic-routes

**Comment by pmcelhaney** [comment]
Oh, that's nice! Yeah I think I'm gonna steal that instead.

**Comment by pmcelhaney** [comment]
A incomplete and buggy implementation of next.js style routes: #2

**Comment by pmcelhaney** [comment]
I think I may have made this harder than it needs to be. With the current implementation, when Counterfact recieves a request for GET `/foo/bar/baz`, it will look for a GET function in `./foo/bar/baz.js`. If it doesn't find one it will look in `./foo/bar.js` and `./foo.js`

With next.js style routing, we don't need to support that fallback pattern, and that should make the code a lot simpler.

**Comment by pmcelhaney** [comment]
This is "done" in the main branch now. (Still need to add more tests, update docs, and update the demo app.)

**Comment by pmcelhaney** [comment]
Docs and demo app are updated and I created #25 for tests.
