### ISSUE TITLE
Malformed vscode URL

### ISSUE THREAD

**Issue by cincauhangus** [pmcelhaney/counterfact#1058]
Hello, I encountered some issues trying to launch IDE from the main page. Note: I am running on Windows.

Incorrect:
https://github.com/pmcelhaney/counterfact/blob/412bb8b607317f63155f45e15ca9a19fe2be45ec/src/client/index.html.hbs#L233

`vscode://file` (missing trailing slash)

Correct:
https://github.com/pmcelhaney/counterfact/blob/412bb8b607317f63155f45e15ca9a19fe2be45ec/src/client/rapi-doc.html.hbs#L24

`vscode://file/` (trailing slash)

**Comment by cincauhangus** [comment]
I found it when i tried to click on the path names on the counterfact page - http://localhost:3100/counterfact/

**Comment by pmcelhaney** [comment]
Oh, I mixed up the correct and incorrect. I'll fix it. Thanks!
