### ISSUE TITLE
Path parameters are all strings at runtime despite the typing

### ISSUE THREAD

**Issue by dethell** [pmcelhaney/counterfact#1116]
The generated GET and POST types for a route are correctly typed based on the OpenApi spec, but they actually pass through Javascript as strings. For example:

```
export const POST: HTTP_POST = $ => {
    const result = $.context.someFunction($.path.id);
    return $.response[200].json(result);
}
```
The IDE says `$.path.id` is a number which is correct. But in my context it really is a string:
```
someFunction(id: number) {
    const record = someLocalArray.find(record => record.id === id);
}
```
The above context function fails to find the record unless I do `parseInt(id)`.

**Comment by pmcelhaney** [comment]
Ah, yes, I vaguely remember thinking "I'm gonna have to address that someday" 😆 

Here's where the change will need to be made. 

https://github.com/pmcelhaney/counterfact/blob/791dbaccba1da00fc36c94b97825c2b42df03805/src/server/koa-middleware.ts#L75

The server will need to have a reference to the OpenAPI object so that it can find the associated route, identify the types of each parameter, and convert to `number` / `boolean` as necessary.

**Comment by pmcelhaney** [comment]
Actually there's already logic to do that:

https://github.com/pmcelhaney/counterfact/blob/aa4dec60c1a316c68ba886b63227274d1331ecda/src/server/registry.ts#L82-L93

**Comment by pmcelhaney** [comment]
Here's the unit test covering that functionality. 

https://github.com/pmcelhaney/counterfact/blob/aa4dec60c1a316c68ba886b63227274d1331ecda/test/server/dispatcher.test.ts#L562-L666

Can you double check that it's not a mistake in your OpenAPI spec? Also make sure that you're passing the OpenAPI spec into the CLI.

**Comment by pmcelhaney** [comment]
@dethell can you share the affected path from your OpenAPI file?

**Comment by dethell** [comment]
Sure. The path is:
```
"/Companies/{id}/ProductStatus/{actionId}": {
```
and the parameters are:
```
"parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Unique Channel Company Id.",
                        "format": "int32",
                        "x-nullable": false
                    },
                    {
                        "type": "integer",
                        "name": "actionId",
                        "in": "path",
                        "required": true,
                        "description": "Product Feature Id.",
                        "format": "int32",
                        "x-nullable": false
                    },
                    {
                        "type": "string",
                        "name": "status",
                        "in": "query",
                        "required": true,
                        "description": "Product Feature status to be modified.",
                        "x-nullable": true
                    }
                ],
```

**Comment by pmcelhaney** [comment]
Release 1.1.5 is going out now.
