### ISSUE TITLE
Remove basePath and create $ref concept

### ISSUE THREAD

**Issue by KameronKales** [pmcelhaney/counterfact#118]
Specification.js currently relies on basePath references that use the local file system. We need a way to load remote and local files the same (with the rest of the code not caring about where the file contents came from). 

We can use this concept https://swagger.io/docs/specification/using-ref/ to get this working. Ill update this story with more details as I get started.

**Comment by pmcelhaney** [comment]
Thanks! If there's a reason `Specification()` takes a `basePath` in its constructor, I don't remember what it was now. The more I look at, the more I think _this makes no sense_.

The constructor probably doesn't need any arguments. `requirementAt()` should take a URI and optional base URL (for when the `$ref` is a relative link). `loadFile()` should take a URL, either an `http[s]://` URL or a `file://' URL.
