### ISSUE TITLE
Swagger UI posts to the "host" from the spec instead of localhost

### ISSUE THREAD

**Issue by dethell-jh** [pmcelhaney/counterfact#304]
I have Counterfact spun up and it has processed our API, successfully rendering the Swagger UI. When I try to execute any of our endpoints instead of posting them against the counterfact server on localhost, it posts them against the URL specific in the `"hosts"` key in the openapi file.

**Comment by dethell-jh** [comment]
Entering `localhost:3100` for the `"hosts"` key does correctly hit the local server.

**Comment by pmcelhaney** [comment]
That's because I was originally targeting OpenAPI 3, which puts the hosts under `servers`.

https://github.com/pmcelhaney/counterfact/blob/3ad1e91161dae681ac208b314a3756d33d555096/src/server/start.js#L22-L27

To support OpenAPI 2, I think all we need to is add one line:

```js
openApiDocument.host = `//localhost:${port}`; 
```

**Comment by dethell-jh** [comment]
Ok, tested this change locally and it works. Created a PR: https://github.com/pmcelhaney/counterfact/pull/309
