### ISSUE TITLE
All requests return Error: not acceptable

### ISSUE THREAD

**Issue by DorelBarbu** [pmcelhaney/counterfact#491]
Hello,

I have been following the quick start guide and started the pet store mock server. However, all the requests I am making are returning `406: Not acceptable`. Is there any way I can fix this issue?

Also getting this error before the REPL loads:

```
Error loading /Users/dorelbarbu/api/paths/pet/findByTags.ts:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/dorelbarbu/api/paths/pet/findByTags.ts
```

Thank you!

**Comment by pmcelhaney** [comment]
Hi @DorelBarbu, sorry about the delay. That issue is fixed now.
