### ISSUE TITLE
Generate classes for each component

### ISSUE THREAD

**Issue by pmcelhaney** [pmcelhaney/counterfact#529]
Currently Counterfact generates code like this:

```ts
export const GET: HTTP_GET = ($) => {
  return $.response[200].random();
};
```

I find myself almost always changing it to code like this:

```ts
import type { Pet } from "../../models/pet.ts";

export const GET: HTTP_GET = ($) => {
  const pet: Pet = {
    id: 1,
    name: "doggie",
  };

  return $.response[200].json(pet)
};
```

It would be useful if Pet was a class instead of just a type:

```ts
import { Pet } from "../../models/pet.ts";

export const GET: HTTP_GET = ($) => {

  return $.response[200].json(new Pet({
    id: 1,
    name: "doggie",
  }))
};
```

Now imagine if the Pet class was automatically generated. The original generated code which returns a random pet could look like this:

```ts
import { Pet } from "../../models/pet.ts";

export const GET: HTTP_GET = ($) => {
  return $.response[200].json(Pet.random());
};
```

Now we can see the type of the response and we already have the Pet class imported.

I would want `pet.ts` to be a file that we can edit -- it's generated once but not overwritten when the OpenAPI schema changes. That can be achieved by making the implementation look like this:

```ts
import { Pet as OpenApiPet } from "../generated/components/Pet.ts";

export class Pet extends OpenApiPet {

}
```

We would need to account for the case where an operation can return one of multiple schemas. Maybe something like this:

```ts
import { Dog } from "../../models/dog.ts";
import { Cat } from "../../models/cat.ts";

export const GET: HTTP_GET = ($) => {
  return $.response[200].json($.oneOf(Dog.random(), Cat.random()));
};
```

**Comment by dethell-jh** [comment]
I like the PR, but I'd probably name the Components something generic enough to be used by the consumer's main codebase so I'd drop the `OpenApi` prefix so that in the end codebase, if the user chose to use the generated types they aren't too cumbersome.

**Comment by pmcelhaney** [comment]
Remembered now why I didn't do this in the first place. The response isn't necessarily an object. It could be any array or a primitive.

Still, it would be nice if this line was added automatically:

```ts
import type { Pet } from "../../models/pet.ts";
```
