### ISSUE TITLE
Generate a mock server with routes prefix

### ISSUE THREAD

**Issue by xvladqt** [pmcelhaney/counterfact#636]
In my specification, all the routes are specified without a global prefix (/api/v1 in my case), but OpenAPI 3 has the ability to specify it through [servers](https://swagger.io/docs/specification/api-host-and-base-path/), counterfact ignores them.

Is it possible to somehow specify this prefix for the generated routers? Maybe it should be done through the command arguments?

**Comment by pmcelhaney** [comment]
Hi @xvladqt, that sounds reasonable. I just to make sure I understand correctly what you're asking for. 

If the OpenAPI spec has `/hello-world` you would like the route to be served from `http://localhost:3000/api/v1/hello-world` instead of `http://localhost:3000/hello-world`?

And that would be accomplished by adding a CLI parameter like `--prefix /api/v1`?

**Comment by pmcelhaney** [comment]
Oh, and there are two ways to accomplish that. Either the generated code can put everything under an `paths/api/v1` instead of `paths` or the generated code is the same but the server maps `/api/v1/hello-world` to `paths/hello-world.ts`. Which do you prefer?

**Comment by xvladqt** [comment]
> If the OpenAPI spec has `/hello-world` you would like the route to be served from `http://localhost:3000/api/v1/hello-world` instead of `http://localhost:3000/hello-world`?
> 
> And that would be accomplished by adding a CLI parameter like `--prefix /api/v1`?

Hi, @pmcelhaney. Yes, that would be nice

> Either the generated code can put everything under an `paths/api/v1` instead of `paths` or the generated code is the same but the server maps `/api/v1/hello-world` to `paths/hello-world.ts`. Which do you prefer?

Second better, i think. Must be easier to implement and less file nesting. First solution does not have much sense because it's global prefix, for all paths.

**Comment by pmcelhaney** [comment]
Hi @xvladqt, this feature is in the latest release, version 0.30.0. Try it out and let me know if that works for you!
