### ISSUE TITLE
On Windows, the import field from path-types to context gets wrong slashes while others are fine

### ISSUE THREAD

**Issue by programm-ingovals** [pmcelhaney/counterfact#788]
```
import type { Context } from "..\..\..\paths\_.context.ts";
import type { ResponseBuilderFactory } from "../../../types.d.ts";
```

I know the easy fix is to switch to a posix, its on the docket.

**Comment by pmcelhaney** [comment]
Ugh! This has bitten me so many times! I'm working around it with a bunch of replaceAll()s. This one, being a type import, must have slipped by the unit tests.

What do you mean by POSIX? I know what POSIX is -- at least at high level -- but I'm what exactly it is you're saying is on the docket?

Thanks for letting me know about this!
