### ISSUE TITLE
Prefix missing from Swagger

### ISSUE THREAD

**Issue by IngoVals** [pmcelhaney/counterfact#820]
Run counterfact with --prefix /something

/something prefix is missing from Swagger

**Comment by dethell** [comment]
Can you elaborate here? Are you saying if the OpenApi spec is missing a prefix you want Counterfact to add it?

**Comment by IngoVals** [comment]
I haven't given this much thought. But as I understand it OpenAPI is relative to some basepath.

In most cases this basepath is just the domain

`https://myfancyapi.com/`

But in some cases it could be relevant to a prefixed url

`https://bigcorp.com/employeeGateway/`

As I understand it openAPI will not mention this `employeeGateway `in any way, all paths are just appended to the end of the url.

For Counterfact, the basepath is by defauly `localhost:3100` so our paths will be added to it. Say our internal api paths are `/api/person/1` the resulting url will be `http://localhost:3100/api/person/1`

When I start up Counterfact I can add a prefix, using `--prefix` So if I add /employeeGateway Counterfact is available at 

`http://localhost:3100/employeeGateway/api/person/1`

This will ensure that I can more easily change from a production and mock api on a running client.

However if I go into Swagger and try out I get 404 because swagger tries out the normal path.

**Comment by dethell** [comment]
A recent PR updated CF to support the `basePath`: https://github.com/pmcelhaney/counterfact/pull/797

So now if your spec has a `basePath` included, and if your client includes that path in its requests, Counterfact will silently handle it correctly. Let me know if that meets this need.

**Comment by pmcelhaney** [comment]
> This will ensure that I can more easily change from a production and mock api on a running client.

There's a better way. You can have Counterfact proxy to the production server. You can then switch between mocks and the proxy to production at runtime. The client code doesn't need a mechanism to switch back and forth at runtime.  

I have big plans to build on this feature. You'll be able to have some endpoints point to production while others are mocked. You'll be able to flip the switch at runtime through a GUI that also serves as an alternative to Postman or Swagger UI which is easier to use. 

I'm typing on my phone so I can't easily link to the docs, but please let me know if that makes sense and fits your use case.

**Comment by pmcelhaney** [comment]
@IngoVals What do you think? Do you still have concerns or can we close this issue?

**Comment by IngoVals** [comment]
What about the prefix attribute in Counterfact, if the plan is to support that still you could just try it out. Run counterfact, with a prefix, open up the swagger endpoint, and try to run an endpoint.

Unless I'm missing something this will not work, which is probably not what we want.

**Comment by pmcelhaney** [comment]
You're right! I forgot that before the OpenAPI doc is passed to Swagger, a URL is injected into the servers object.

https://github.com/pmcelhaney/counterfact/blob/291beab83e53da2c3e8bae0177b829ed516bf5a8/src/server/openapi-middleware.ts#L19-L22

That URL should include the prefix, which is stored as `config.routePrefix`. If we add a routePrefix argument to the `openApiMiddlware()` function and pass in `config.routePrefix` from [create-koa-app.ts](https://github.com/pmcelhaney/counterfact/blob/main/src/server/create-koa-app.ts#L23), we can append the prefix to the `url` in the above code snippet. 

Note that the type of the `Config` object is missing `routePrefix`, a mistake that needs to be corrected.
