### ISSUE TITLE
Endpoint gives error attempting to return 200 status

### ISSUE THREAD

**Issue by dethell** [pmcelhaney/counterfact#828]
Getting this 500 error from an endpoint that does have a valid 200 response defined:

`The Open API document does not specify a response for status code 200`

**Comment by dethell** [comment]
Well, I stripped my OpenApi doc down to just the failing endpoint and it works fine. Digging in further to find out why it fails as part of the larger set and then I'll report back.

**Comment by dethell** [comment]
Ok, I have it now. Use the attached open spec. There is a single endpoint starting with MyCompanies. If you run the swagger UI execute function it will work correctly. However, if you execute the command as a cURL call and change the case of the path it fails. Note the call below where `MyCompanies` is written as `myCompanies`.

```
curl -X 'GET' \
  'http://localhost:3100/myCompanies/4817/Accounts?type=createDomestic' \
  -H 'accept: application/json'
```

The Counterfact `dispatcher` assumes an exact match in the `operationForPathAndMethod` function so when it looked for `/myCompanies/{id}/Accounts` it found no match, but if you issue the curl against `/MyCompanies/{id}/Accounts` it works just fine.

I realize that case sensitivity in url paths is not consistent on the web. Windows servers such as IIS are case insensitive but often other platforms would consider `/MyCompanies` and `/myCompanies` as different paths. So I'm not sure what CF should do here. From what I've researched it seems most REST API developers recommend assuming your paths are case insensitive so that a server won't really care about casing. That helps for users who might enter the wrong case.

I recommend we just change `dispatcher` to ignore case when looking in the paths object. I'll put together a PR if that seems good to you.

[openapi-v2.json](https://github.com/pmcelhaney/counterfact/files/14865449/openapi-v2.json)

**Comment by pmcelhaney** [comment]
I know we've chatted about case sensitivity before. I think it's better to be conservative by default and assume production will be case sensitive. 

But I'm not opposed to an option that turns off case sensitivity.

**Comment by dethell** [comment]
I agree that we should be conservative by default. I'm going to go ahead and add a PR to add the option since it is a valid use case and we can't always ask the upstream consumers of an API to change their call points.

**Comment by dethell** [comment]
Got a good way into this PR (all the `dispatcher.ts` changes) when I realized we are already attempting to be case insensitive on paths. Check out `module-tree.ts`:

```
  private buildMatch(
    directory: Directory,
    segment: string,
    pathVariables: { [key: string]: string },
    matchedPath: string,
  ) {
    const match =
      directory.files[segment.toLowerCase()] ??
      Object.values(directory.files).find((file) => file.isWildcard);
```
In there we match `directory.files` on the lower case of `segment`. This appears to me that part of the codebase cares about case and part does not. I noticed this because of the tests I was adding to `dispatcher`. It was still passing on invalid-case paths because the `module-tree` matcher was finding the paths.

Thoughts? Do we just make it case-insensitive across the board without a config option or do we add the config option and update `module-tree` to care about case?

**Comment by dethell** [comment]
Actually, the real place in `module-tree` is line 75 and following where it adds the segment to the directory as lower case:
```
this.addModuleToDirectory(
      directory.directories[segment.toLocaleLowerCase()],
      remainingSegments,
      module,
    );
```

**Comment by dethell** [comment]
Given the above I think we just drop the idea of an input option and just make `dispatcher` not care about case.

**Comment by dethell** [comment]
To aid discussion, I added a PR that just updates the logic without the new option for ignoring case. This just brings `dispatcher` into line with the already case-insensitive matching of the `Registry`
