### ISSUE TITLE
Ability to run Counterfact without OpenAPI

### ISSUE THREAD

**Issue by pmcelhaney** [pmcelhaney/counterfact#834]
Counterfact works fine without an OpenAPI description. It just won't generate code for you. You have to create JavaScript* files manually under the `paths` directory. The easiest way to implement is to supply an empty OpenAPI object if no file is given. In the CLI, a `-` can stand for the empty OpenAPI object.

```sh
npx counterfact - ./api 
```

The `-` could become the default value for the OpenAPI file path argument. If you're happy for files to be in the default location (the current working directory), it could be run with no arguments at all.

```sh
npx counterfact
```

----

*Either JavaScript or TypeScript would work, but TypeScript without the automatically generated types would not be fun.

**Comment by dethell** [comment]
Running without OpenApi would easier with one of the archived recording features:

https://github.com/pmcelhaney/counterfact/issues/451
or
https://github.com/pmcelhaney/counterfact/issues/452

Then you could just turn on proxy, start recording, and have it build out your files (if not your types). Just mentioning here to possibly bump up those archived feature requests for later discussion.

**Comment by pmcelhaney** [comment]
This was implemented in 0.41.0
