### ISSUE TITLE
Support OpenAPI reusable responses in global components object

### ISSUE THREAD

**Issue by brianlaframboise** [pmcelhaney/counterfact#838]
The following configuration works (`<counterfact root>/components/Error.ts` is generated):

```yaml
paths:

  /path-one:
      responses:
        "400":
          description: The request is malformed and so cannot be processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /path-two:
      responses:
        "400":
          description: The request is malformed and so cannot be processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:

    Error:
      title: Error
      description: A generic error message suitable for 4xx and 5xx responses
      type: object
      properties:
        errorCode:
          type: string
          description: A machine readable error code
        message:
          type: string
          description: A detailed description of the error
      required:
        - message
```

According to [Reusing Responses](https://swagger.io/docs/specification/describing-responses/), I should be able to extract common schemas under `components/responses` like so:

```yaml
paths:

  /path-one:
      responses:
        "400":
          $ref: "#/components/responses/BadRequest"

components:

  responses:

    BadRequest:
      description: The request is malformed and so cannot be processed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:

    Error:
      title: Error
      description: A generic error message suitable for 4xx and 5xx responses
      type: object
      properties:
        code:
          type: string
          description: A machine readable error code
        message:
          type: string
          description: A detailed description of the error
      required:
        - message
```

However, with that configuration I have a few problems.

First, no `Error.ts` type is generated.

Second, the `*.types.ts` file is missing expected types. Specifically, the `content` has `never` type:

```ts
export type HTTP_POST = (
  $: OmitValueWhenNever<{
[...]
    response: ResponseBuilderFactory<{
      400: {
        headers: never;
        requiredHeaders: never;
        content: never;
      };
```

whereas previously it was correct:

```ts
      400: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: Error;
          };
        };
      };
```

Note this isn't strictly a blocker to using counterfact (for me) as I can avoid the refactoring and keep the duplication to get counterfact to do the right thing. However, for others who may not be in control how the spec is written, this could be a problem.

If I may speculate on the root cause, I presume this is because counterfact has its own bespoke OpenAPI parser? If so, a quick search has found tools like https://www.npmjs.com/package/@readme/openapi-parser which may provide a complete parser that handles all the `$ref`s and other subtleties of the OpenAPI spec. I only point this out as this specific issue may be fixed, but it does give me pause as to what other issues I may encounter using counterfact with specs that use lesser-known parts of OpenAPI. Of course, switching out parsers is likely a non-trivial amount of work.

**Comment by pmcelhaney** [comment]
Thanks. It uses js-yaml, which theoretically should resolve all of the `$ref`s. I'm not sure what went wrong here, but I'll put together a test case and figure it out. 

> it does give me pause as to what other issues I may encounter using counterfact with specs that use lesser-known parts of OpenAPI

I hear you. It's been a long road getting to the point where almost all of the OpenAPI spec is handled correctly. At this point I have a high level of confidence in the unit tests and the code has proven to be robust enough that I'm able to address edge cases as they come up without too much difficulty.

Having said that, after 1.0, I'm planning to rewrite the code generator. With a massive suite of characterization tests to make sure that doesn't regress anything.

**Comment by pmcelhaney** [comment]
Actually, I see where the problem is. The code generator handles "$ref", but only inside of a schema object. Should be a fairly straightforward fix. Thanks for bringing it to my attention!

**Comment by pmcelhaney** [comment]
In theory, #843 will fix it. I need to verify that the reported use case is truly covered and add tests.

**Comment by pmcelhaney** [comment]
That wasn't quite what was needed but I see the way forward now. Writing it down for my own reference. 

- only SchemaCoder and SchemaTypeCoder handle $ref. That if statement needs to be pulled up to Coder
- add an intermediate TypeCoder class which all TypeCoders will extend. All it does is identify that it outputs type code rather than JS code
- remove importType(), use that new type property to determine if the type keyword needs to be added to the import statement 
- split Operation[Type]s coder out from OperationCoder because those are two distinct objects in the spec
