### ISSUE TITLE
Switch to ESLInt flatconfig

### ISSUE THREAD

**Issue by pmcelhaney** [pmcelhaney/counterfact#842]
[Migrate to the new "flatconfig" configuration format](https://eslint.org/docs/latest/use/migrate-to-9.0.0), which is the default for ESLint 9. 

#839

I'm not sure if we can switch to the new format before all of the dependencies are switched over. If not, it will probably be a long time before we can switch. But we should set the environment variable that causes ESLint to use the old format so we can stay on the latest version. 

I wonder if we can throw the old file at ChatGPT and ask it to output the new format.

**Comment by dethell** [comment]
I took a shot at having Copilot convert the file, but it wasn't right. Maybe a good starting point, but not a working conversion.

**Comment by pmcelhaney** [comment]
Done
