### ISSUE TITLE
Put all generated types under a "types" directory

### ISSUE THREAD

**Issue by pmcelhaney** [pmcelhaney/counterfact#855]
A fairly simple change:

- `path-types` -> `types/paths`
- `components` -> `types/components`
- `paths` -> `routes`

I think it will be easier to understand what's what. The structure of the types directory should resemble the structure of the OpenAPI spec. And "routes" is a clearer indicator of what the directory contains. 

I don't like to catch people off guard with disruptive changes like this. If we're going to do it, it should be before 1.0.

**Comment by pmcelhaney** [comment]
Maybe there can be a grace period with backwards compatibility. If a `paths` directory is detected, Counterfact will continue to use the old structure but print a warning with migration instructions. (It's a matter of renaming a couple of directories and then doing a search and replace.)

**Comment by dethell** [comment]
I do think the renaming is better. Not so worried about the breaking change, pre-1.0 but rather than supporting both, what about a migration script that just moves everything to the new places?

**Comment by pmcelhaney** [comment]
Could write a migration script. I just don't want to inflict unexpected changes on people. 

After 1.0 I'm going to start promoting so I'd rather get this sort of thing out of the way first.
