### ISSUE TITLE
Better explanation of why generated code should be committed to version control

### ISSUE THREAD

**Issue by pmcelhaney** [pmcelhaney/counterfact#856]
Is there any good reason to commit generated code for types to version control? In the documentation I wrote that those files should be committed, but now I can't remember what my reasoning was. 

If the types code isn't committed, I think that would alleviate confusion when a new version of Counterfact generates types differently from the previous version. 

Counterfact creates a `.gitignore` file for the `.cache` directory and that seems to work fine. I can't think of a reason we shouldn't add the types directories to that file.

**Comment by dethell** [comment]
I would think just committing the components and paths would be enough. Types are ephemeral since they are regenerated anyway.

**Comment by pmcelhaney** [comment]
Components are also types. 

Okay, I remember the problem with not committing types. The moment you pull down the repo it's "broken" because there are references to type files that aren't there. In theory, you could run Counterfact and regenerate them in seconds. And the OpenAPI file might be outside of the repo, so there's no guarantee that running Counterfact again will produce exactly the same code. 

I've changed the title of this issue to add more clarity in the documentation rather than change the code.

**Comment by pmcelhaney** [comment]
It's explained in https://github.com/pmcelhaney/counterfact/blob/main/docs/faq-generated-code.md
