### ISSUE TITLE
Ability to mark a file as manually maintained (do not overwrite)

### ISSUE THREAD

**Issue by pmcelhaney** [pmcelhaney/counterfact#891]
Inspired by #890 

There may be cases where a particular file should not be overwritten by Counterfact. In the above case, it's due to a bug which I intend to fix ASAP. Unfortunately, the work-around -- fixing the code manually -- doesn't work, because Counterfact keeps overwriting the file.

**Comment by pmcelhaney** [comment]
I think the code is stable enough now that the value of this work-around no longer outweighs the complexity it would add.

**Comment by dethell** [comment]
Agreed. Let's close it.
