### ISSUE TITLE
Context file cannot find modules in counterfact 0.40+ 

### ISSUE THREAD

**Issue by brianlaframboise** [pmcelhaney/counterfact#906]
I upgraded from `0.38.3` to `0.42.0` to try out the new hot reloading changes (#835). Unfortunately, the app no longer works at all.

## Setup
I have custom counterfact code in a sub-folder of my little UI project, like so:
```
my-ui/
	...files...
	package.json
	counterfact/
		path-types/
		paths/
			mocks/ <-- my custom code
				session-manager.ts
			_.context.ts
		package.json
```

I have a lot of custom code in that `/mocks` directory, but I'm simplifying things here to a minimal test case.

### counterfact/package.json
```json
{
	"name": "my-ui-counterfact",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"mockapi": "counterfact ../path/to/my/openapi.yaml ."
	},
	"devDependencies": {
		"counterfact": "^0.42.0"
	},
	"type": "commonjs"
}
```

### counterfact/paths/_.context.ts
```ts
import { SessionManager } from './mocks/session-manager';

const sessionManager = new SessionManager();

export class Context {
	someCustomFunction(): any {
		return sessionManager.toString();
	}
}
```

### counterfact/paths/mocks/session-manager.ts
```ts
class SessionManager {}
export { SessionManager };
```

## Error

With all that in place, when I run `my-ui/counterfact> npm run mockapi`, I get the following:

```
...
Watching for changes
Starting server
Starting REPL, type .help for more info

Error loading /Users/.../my-ui/counterfact/.cache/_.context.cjs:
Error: Cannot find module './mocks/session-manager'
Require stack:
- /Users/.../my-ui/counterfact/.cache/_.context.cjs
- /Users/.../my-ui/counterfact/node_modules/counterfact/dist/server/uncached-require.cjs
```

Please let me know if my setup is unsupported/I'm doing something wrong, if you cannot reproduce, or if this is a genuine bug.

**Comment by pmcelhaney** [comment]
Thanks for letting me know! The issue is Counterfact expects the imported file to have a `.js` extension. 

```ts
import { SessionManager } from './mocks/session-manager';
```

If you add the `.js` extension it should work. 

```ts
import { SessionManager } from './mocks/session-manager.js';
```

Adding the `.js` extension is considered a best practice. I'll link a reference when I find it. However, I don't see any value in being pedantic about it. I'll fix the code so that either no extension or `.ts` works.

**Comment by pmcelhaney** [comment]
Fixed in 0.42.1. Please let me know if that does the trick (and the hot reload works)!

**Comment by brianlaframboise** [comment]
Ah yes, my inexperience with node is showing. Sure enough, I added file extensions and it worked! I see how node (and its module systems) are more browser-like and require full paths to resources (unlike other languages where file extensions are omitted, which was my naive assumption).

I'll stick with explicit extensions, but I'm sure someone out where will appreciate the flexibility.

I tested it out hot reloading, and indeed it works like a charm now! Lightning fast and seamless. Well done.

I consider this issue closed.

**Comment by pmcelhaney** [comment]
Awesome! At this point it should work even without the file extension. Any valid TypeScript code should work. If you run into anything that doesn't work, or behaves in a way that is not obvious, please let me know. I want this tool to be absurdly intuitive. 

Thanks again for the feedback!
